on:
    push:
    pull_request:

env:
    ROS_DISTRO: humble
    TARGET_PACKAGES: cube_msgs cube_den_msgs

jobs:
    build:
      runs-on: ubuntu-latest
      container: ros:humble
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
  
        - name: Build
          uses: autowarefoundation/autoware-github-actions/colcon-build@v1
          with:
            rosdistro: $ROS_DISTRO
            target-packages: $TARGET_PACKAGES

        - name: Test
          uses: autowarefoundation/autoware-github-actions/colcon-test@v1
          with:
            rosdistro: $ROS_DISTRO
            target-packages: $TARGET_PACKAGES
